### PR TITLE
Add long_type_number and long_type_bigint parameters.

### PR DESCRIPTION
**Pull request by vicb**
Hey @timostamm here is a draft PR. 

I have a couple questions for you.

What do you think about the style `--long_type=number|string|bigint` ?
I actually prefer it over `long_type_number`, ...
But it would probably makes sense to do the same for `---client=...`, `--optimize` and `--force_optimize`.

So I guess up to you to take the decision as the maintainer of this lib.

(If you decide for `key=value` then it would make sense to add a `values: string[]` in the parameter spec to automate the declaration).

My second question is about testing:

When I run `make` in the root folder I end up with some error:

```
[...]
@protobuf-ts/runtime-rpc: 'clean' done
@protobuf-ts/plugin-framework: 'clean' done
@protobuf-ts/runtime-rpc: es6 done
@protobuf-ts/plugin-framework: es6 done
@protobuf-ts/runtime-rpc: cjs done
@protobuf-ts/runtime-rpc: 'test-node' ...
@protobuf-ts/plugin-framework: cjs done
@protobuf-ts/plugin-framework: protoc not found. Looks like something went wrong during installation.
@protobuf-ts/plugin-framework: make[1]: *** [../test-fixtures/all.descriptorset] Error 1
```

I still have to track down the root cause but one possible problem is that your `protoc` has the same name as google `protoc` so depending on the `PATH` on or the other will be launched (as node install your `protoc` in `/usr/local/bin`).

### CODE REVIEW

**Comment by timostamm** [comment]
```
@protobuf-ts/plugin-framework: protoc not found. Looks like something went wrong during installation.
@protobuf-ts/plugin-framework: make[1]: *** [../test-fixtures/all.descriptorset] Error 1
```

To build the project, you need protoc installed and ready on the PATH. 

The error message is from the protoc wrapper (packages/protoc).

But the Makefile just calls `protoc`, which should run the real protoc. 

> as node install your protoc in /usr/local/bin

Hm. How did that happen? Did you install the plugin globally? Could you do a 

```shell
cd packages/plugin-framework
which protoc
```

It outputs `/usr/local/bin/protoc` for me (which is where I installed google protoc).

**Comment by vicb** [comment]
I might have copied the wrong proto in `/usr/local/bin/proto` (the plugin wrapper instead of google protoc).

I have deleted it (google one is in ~/bin) and it works better.

**Comment by vicb** [comment]
I do have this error now

```
@protobuf-ts/test-generated: **************************************************
@protobuf-ts/test-generated: *                     Errors                     *
@protobuf-ts/test-generated: **************************************************
@protobuf-ts/test-generated: 1) generated client style promise duplex-streaming
@protobuf-ts/test-generated:   - Unhandled promise rejection: RpcError: user cancel
@protobuf-ts/test-generated:   Code: CANCELLED
@protobuf-ts/test-generated: 2) generated client style promise client-streaming
@protobuf-ts/test-generated:   - Unhandled promise rejection: RpcError: user cancel
@protobuf-ts/test-generated:   Code: CANCELLED
@protobuf-ts/test-generated: Executed 230 of 230 specs (2 ERRORS) in 4 secs.
```

**Comment by timostamm** [comment]
This could be a timing issue that only pops up in some situation.  Circle-CI and my machine pass. Having a closer look tomorrow.

After changing something in `packages/plugin`, you can run `make build` in this directory. 

Then you can manually run the plugin with protoc: 

```shell
protoc --plugin bin/protoc-gen-ts -I ../test-fixtures --ts_out ~/ --ts_opt long_type_string ../test-fixtures/msg-scalar.proto
```

**Comment by vicb** [comment]
Sure, no rush.

The more I think about `--long_type=number|string|bigint` the more I like it.

- we could add the `values: []` in the parameter spec and let the framework enforce that there is only one value,
- it is also possible to support `_` instead of `=` for backward compatibility.

Let me know in which direction this PR should go.

Thanks.

**Comment by timostamm** [comment]
Sorry for the delay...

I see your point with `--long_type=number`. But I think the case is not as clear-cut. You would need to type out `--ts_opt=long_type=number`, which has always felt a little bit off to me. 

After playing around with grpc web and seeing commands like 

```shell
$ protoc -I=$DIR echo.proto \
  --js_out=import_style=commonjs,binary:$OUT_DIR \
  --grpc-web_out=import_style=typescript,mode=grpcwebtext:$OUT_DIR
```

... I made the decision to only use flags for plugin parameters, to keep the usage as simple as possible. 

Maybe this decision was wrong - protobuf-ts is still too young to really tell. If it turns out that key-value pairs are actually the better choice, I am totally fine with changing the style. 

But right now, I think we should stick with the convention of flags as it is. They have some benefits that are not immediately obvious:
- [parsing parameters](https://github.com/timostamm/protobuf-ts/blob/e9b591edd5ec101eb4e2d90965e15c319328f10b/packages/plugin/src/protobufts-plugin.ts#L76) is typesafe: If you try to access a parameter that is not declared, you get a compile time error. 
- if a user makes a type, usage information is [automatically generated](https://github.com/timostamm/protobuf-ts/blob/e9b591edd5ec101eb4e2d90965e15c319328f10b/packages/plugin-framework/src/plugin-base.ts#L136)

Replacing this may require more effort than anticipated. I would prefer to gather more experience and community feedback about plugin parameters first. Add more parameters requested by users (just like you did). Then decide whether switching the style is beneficial.

**Comment by vicb** [comment]
> Sorry for the delay...

No worries. A few days is not really what I would call a "delay". We all have many things to do. Your library is super helpful (I used it on 2 repos already) and it's nice of you to open source it and maintain it. I also really appreciate your detailed responses each time. Thanks a lot.

> You would need to type out `--ts_opt=long_type=number`, which has always felt a little bit off to me.

I kind of agree with this point.

However I think the parameter doc would be nicer if all `long_type` are documented together instead of being being 3 different docs.

Thinking ahead a lot of projects (babel, eslint, jest, ...) have the options to use parameters or a js/json file for configuration. If more options are added over time (to generate/disable read, write or json, may be const enum, ...) then it would also be nice to support that.

Finally you can also write `--ts_opt long_type=number` to make it look less odd.

>parsing parameters is typesafe: If you try to access a parameter that is not declared, you get a compile time error.
>if a user makes a type, usage information is automatically generated

I don't immediately see a reason why this could not be supported with the k=v scheme ?

>  I would prefer to gather more experience and community feedback about plugin parameters first. Add more parameters requested by users (just like you did). Then decide whether switching the style is beneficial.

Sounds like a perfectly reasonable thing to do. Thanks for one more super detailed answer.

I am going to update this PR to use `long_type_number`.

**Comment by vicb** [comment]
Hey Timo,
I have updated the PR following your answer.

**Comment by timostamm** [comment]
Thanks for the contrib, Vic!

**Pull request merged**
